#!/usr/bin/env python 3
#-*-conding-utf-8 -*-

product_list=[
	('Mac',9000),
    ('kindle',800),
    ('tesla',900000),
    ('python book',105),
    ('bike',2000),]

saving=input('please input your money:')
if saving.isdigit():
	saving=int(saving)
	shopping_car=[]
	while True:
		for x,v in enumerate(product_list,1):
			print(x,'>>>',v)
		choice=input('请您输入您想要购买的商品[q退出]:')
		#判断choice里面是不是字符串型的数字
		if choice.isdigit():
			#购买商品
			choice=int(choice)
			if choice>0 and choice<len(product_list)+1:
				if product_list[choice-1][1]<saving:
					saving-=product_list[choice-1][1]
					print('已将%s添加到您的购物车里面去了'%(product_list[choice-1][0]))
					shopping_car.append(product_list[choice-1][0])   #这里应该 不要再用一个变量来得到结果，append前面不可以再用一个变量来得到列表
				else:
					print('您的余额不足,还剩%s元'%(saving))
			else:
				print('请您输入1-%s来购买您看中的商品!'%(len(product_list)))
		#q退出
		elif choice=='q':
			print('---------您已将购买如下商品-----------')
			for i in shopping_car:
				print(i)
			print('您还剩%s元'%(saving))
			break
		else:
			print('invalid input')



